export const VALIDATION_ERROR = "VALIDATION_ERROR";
export const AUTHENTICATION_ERROR = "AUTHENTICATION_ERROR";
export const AUTHORIZATION_ERROR = "AUTHORIZATION_ERROR";
export const NOT_FOUND_ERROR = "NOT_FOUND";
export const RATE_LIMIT_ERROR = "RATE_LIMIT_ERROR";
export const INTERNAL_ERROR = "INTERNAL_ERROR";
export const INVALID_JSON = "INVALID_JSON";
export const SERVICE_UNAVAILABLE_ERROR = "SERVICE_UNAVAILABLE";
